version: "3.9"

services:
  tcp-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tcp-server
    ports:
      - 4242:4242
    networks:
      - textprotocol
  lbl:
    image: nginx
    container_name: load_balancer
    depends_on:
      - tcp-server
    ports:
      - 8080:8080
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - textprotocol

networks:
  textprotocol:
